spring:
  application:
    name: product-service
    
server:
 port : 8081
  
eureka:  client:
    register-with-eureka: true
    fetch-registry: true    service-url:
      defaultZone: http://localhost:8761/eureka/
  
  cloud:
    config:
      enable: true
      uri: http://localhost:8888      
management:
  endpoints:
    web:
      exposure:
        include: "*"